version: 2
updates:
  - package-ecosystem: 'maven'
    directory: 'stackrox-container-image-scanner/'
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.webjars*"

  - package-ecosystem: 'gradle'
    directory: 'functionaltest-jenkins-plugin/'
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: 'daily'
