version: 2
updates:
  - package-ecosystem: 'maven'
    directory: 'stackrox-container-image-scanner/'
    schedule:
      interval: "daily"
    reviewers:
      - "stackrox/backend-dep-updaters"

  - package-ecosystem: 'gradle'
    directory: 'functionaltest-jenkins-plugin/'
    schedule:
      interval: "daily"
    reviewers:
      - "stackrox/backend-dep-updaters"

