package com.stackrox.jenkins.plugins.services;

import static com.github.tomakehurst.wiremock.client.WireMock.anyUrl;
import static com.github.tomakehurst.wiremock.client.WireMock.equalTo;
import static com.github.tomakehurst.wiremock.client.WireMock.equalToJson;
import static com.github.tomakehurst.wiremock.client.WireMock.ok;
import static com.github.tomakehurst.wiremock.client.WireMock.post;
import static com.github.tomakehurst.wiremock.client.WireMock.serverError;
import static com.github.tomakehurst.wiremock.client.WireMock.urlEqualTo;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.io.IOException;
import java.util.List;

import com.github.tomakehurst.wiremock.client.MappingBuilder;
import com.google.common.collect.ImmutableList;

import com.stackrox.jenkins.plugins.data.ViolatedPolicy;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class DetectionServiceTest extends AbstractServiceTest {

    DetectionService detectionService;

    @BeforeEach
    void beforeEach() {
        detectionService = new DetectionService(client);
    }

    @Test
    public void shouldThrowOn500() {
        MOCK_SERVER.stubFor(post(anyUrl()).willReturn(serverError()
                .withBodyFile("v1/detect/build/error.json")));

        Exception exception = assertThrows(IOException.class, () -> detectionService.getPolicyViolations("nginx:latest"));
        String expected = "Failed build time detection request. Status code: 500. Error: image enrichment error: error getting metadata for image: docker.io/library/jenkins:lts errors: [error getting metadata from registry: \"Public DockerHub\": Failed to get the manifest digest : Head \"https://registry-1.docker.io/v2/library/jenkins/manifests/lts\": http: non-successful response (status=404 body=\"\"), error getting metadata from registry: \"Autogenerated https://registry-1.docker.io for cluster remote\": Failed to get the manifest digest : Head \"https://registry-1.docker.io/v2/library/jenkins/manifests/lts\": http: non-successful response (status=404 body=\"\")]";
        assertEquals(expected, exception.getMessage());
    }

    @Test
    public void shouldThrowWhenNoDataFor200() throws IOException {
        MOCK_SERVER.stubFor(postDetectBuild().willReturn(
                ok().withBody("{}")));
        List<ViolatedPolicy> violations = detectionService.getPolicyViolations("nginx:latest");
        assertEquals(0, violations.size());
    }

    @Test
    public void shouldParseDataFromServer() throws IOException {
        MOCK_SERVER.stubFor(postDetectBuild().willReturn(
                ok().withBodyFile("v1/detect/build/nginx.latest.json")));
        List<ViolatedPolicy> actual = detectionService.getPolicyViolations("nginx:latest");

        List<ViolatedPolicy> expected = ImmutableList.of(new ViolatedPolicy("Docker CIS 4.4: Ensure images are scanned and rebuilt to include security patches",
                        "Images should be scanned frequently for any vulnerabilities...",
                        "MEDIUM",
                        "Images should be re-built ensuring that the latest version of the base images are used..."),
                new ViolatedPolicy("Latest tag", "", "MEDIUM", ""));

        assertEquals(expected, actual);
    }

    @Test
    public void shouldNotFailOnMissingData() throws IOException {
        MOCK_SERVER.stubFor(postDetectBuild().willReturn(
                ok().withBodyFile("v1/detect/build/minimal.json")));
        List<ViolatedPolicy> actual = detectionService.getPolicyViolations("nginx:latest");

        List<ViolatedPolicy> expected = ImmutableList.of(new ViolatedPolicy(null, null, "UNSET", null));

        assertEquals(expected, actual);
    }

    private MappingBuilder postDetectBuild() {
        return post(urlEqualTo("/v1/detect/build"))
                .withHeader("Authorization", equalTo("Bearer {some token}"))
                .withRequestBody(equalToJson("{\"imageName\" : \"nginx:latest\"}"));
    }

}
