name: auto-merge

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: auto-merge
  cancel-in-progress: false

jobs:
  auto-merge:
    name: Enable auto-merge for eligible PRs
    runs-on: ubuntu-latest
    if: github.repository_owner == 'stackrox'

    steps:
      - name: Run auto-merge action
        uses: stackrox/actions/automerge@6691d5c300d4af17546145bdbbb9862c53975af4
        with:
          github-token: ${{ secrets.RHACS_BOT_GITHUB_TOKEN }}
