name: CI

on:
  push:
    branches: [ master ]
    tags:
      - "*"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
    - name: Build with Maven
      run: cd stackrox-container-image-scanner && ./mvnw -B package hpi:hpi cyclonedx:makeAggregateBom
    - uses: release-drafter/release-drafter@v5
      id: release_drafter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Release Asset Linux
      id: upload-release-asset-linux
      uses: gfreezy/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.release_drafter.outputs.id }}
        upload_url: ${{ steps.release_drafter.outputs.upload_url }}
        asset_path: stackrox-container-image-scanner/target/stackrox-container-image-scanner.hpi
        asset_name: stackrox-container-image-scanner.hpi
        asset_content_type: application/octet-stream
    - name: Upload SBOM XML Asset Linux
      id: upload-sbom-xml
      uses: gfreezy/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.release_drafter.outputs.id }}
        upload_url: ${{ steps.release_drafter.outputs.upload_url }}
        asset_path: stackrox-container-image-scanner/target/bom.xml
        asset_name: bom.xml
        asset_content_type: text/xml
    - name: Upload SBOM JSON Asset Linux
      id: upload-sbom-json
      uses: gfreezy/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.release_drafter.outputs.id }}
        upload_url: ${{ steps.release_drafter.outputs.upload_url }}
        asset_path: stackrox-container-image-scanner/target/bom.json
        asset_name: bom.json
        asset_content_type: application/json

