name: CI

on:
  push:
    branches: [ master ]
    tags:
      - "*"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'maven'
    - name: Build with Maven
      run: stackrox-container-image-scanner/mvnw package hpi:hpi --file stackrox-container-image-scanner/pom.xml
    - uses: release-drafter/release-drafter@v5
      id: release_drafter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Release Asset Linux
      id: upload-release-asset-linux
      uses: gfreezy/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.release_drafter.outputs.id }}
        upload_url: ${{ steps.release_drafter.outputs.upload_url }}
        asset_path: stackrox-container-image-scanner/target/stackrox-container-image-scanner.hpi
        asset_name: stackrox-container-image-scanner.hpi
        asset_content_type: application/octet-stream

